// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // IMPORTANT: Replace these placeholder values with your actual Firebase configuration
  // You can get these values from your Firebase Console project settings
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxeQ_jfCVE0fFaQfh_jTwOR3xIkFzvc9I',
    appId: '1:610274763374:web:46c9b78def2b3e9e8ffc7f',
    messagingSenderId: '610274763374',
    projectId: 'ghostroll-3800d',
    authDomain: 'ghostroll-3800d.firebaseapp.com',
    storageBucket: 'ghostroll-3800d.firebasestorage.app',
    measurementId: 'G-VMQFZYRF0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDhjhAMv0GPJMvxvROHb4SC2DNBVShYM', // Real Android API key from your google-services.json
    appId: '1:610274763374:android:3d4db7ca14cdaaf58ffc7f', // Real Android app ID from your google-services.json
    messagingSenderId: '610274763374', // Real sender ID from your iOS plist
    projectId: 'ghostroll-3800d', // Your actual Firebase project ID
    storageBucket: 'ghostroll-3800d.firebasestorage.app', // Your actual storage bucket
    // Note: Android package name is now com.nick.ghostroll
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg1nJhraZW7it0qAseiUqHmb-VO3EhKHQ', // Real iOS API key from your plist
    appId: '1:610274763374:ios:63ec1b7db438bbd68ffc7f', // Real iOS app ID from your plist
    messagingSenderId: '610274763374', // Real sender ID from your plist
    projectId: 'ghostroll-3800d', // Your actual Firebase project ID
    storageBucket: 'ghostroll-3800d.firebasestorage.app', // Your actual storage bucket
    iosBundleId: 'com.nick.ghostroll', // This matches your actual iOS bundle ID
  );
} 