// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _requireEnv('FIREBASE_WEB_API_KEY', _webApiKey),
        appId: '1:610274763374:web:46c9b78def2b3e9e8ffc7f',
        messagingSenderId: '610274763374',
        projectId: 'ghostroll-3800d',
        authDomain: 'ghostroll-3800d.firebaseapp.com',
        storageBucket: 'ghostroll-3800d.firebasestorage.app',
        measurementId: 'G-VMQFZYRF0N',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _requireEnv('FIREBASE_ANDROID_API_KEY', _androidApiKey),
        appId: '1:610274763374:android:3d4db7ca14cdaaf58ffc7f',
        messagingSenderId: '610274763374',
        projectId: 'ghostroll-3800d',
        storageBucket: 'ghostroll-3800d.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _requireEnv('FIREBASE_IOS_API_KEY', _iosApiKey),
        appId: '1:610274763374:ios:63ec1b7db438bbd68ffc7f',
        messagingSenderId: '610274763374',
        projectId: 'ghostroll-3800d',
        storageBucket: 'ghostroll-3800d.firebasestorage.app',
        iosBundleId: 'com.nick.ghostroll',
      );

  static const String _webApiKey =
      String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: '');
  static const String _androidApiKey =
      String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: '');
  static const String _iosApiKey =
      String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: '');
}

String _requireEnv(String name, String value) {
  if (value.isEmpty) {
    throw StateError(
      'Missing $name. Pass it via --dart-define=$name=YOUR_VALUE when running Flutter.',
    );
  }
  return value;
}