// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Development Firebase configuration
  // TODO: Replace with production values before App Store submission
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxGxGxGxGxGxGxGxGxGxGxGxGxGxGxGx',
    appId: '1:123456789012:web:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'ghostroll-app-dev',
    authDomain: 'ghostroll-app-dev.firebaseapp.com',
    storageBucket: 'ghostroll-app-dev.appspot.com',
    measurementId: 'G-ABCDEFGHIJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxGxGxGxGxGxGxGxGxGxGxGxGxGxGxGx',
    appId: '1:123456789012:android:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'ghostroll-app-dev',
    storageBucket: 'ghostroll-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxGxGxGxGxGxGxGxGxGxGxGxGxGxGxGx',
    appId: '1:123456789012:ios:abcdefghijklmnop',
    messagingSenderId: '123456789012',
    projectId: 'ghostroll-app-dev',
    storageBucket: 'ghostroll-app-dev.appspot.com',
    iosBundleId: 'com.nick.ghostroll',
  );
} 